# Site settings
title: "My Last Neuron"
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "A blog about Linux, Machine Learning, Games, etc..." 
baseurl: ""
url: "http://david-berthelot.github.io"
# twitter_username: SBootstrap
github_username:  david-berthelot
# email_username:  your-email@yourdomain.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
